name: Deploy to Firebase Function

on:
  push:
    branches:
    - main

jobs:
  main:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@master
    - name: Create Service Account key
      run: echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}' > $HOME/gcloud.json
    - name: Export Service Account  
      run: export GOOGLE_APPLICATION_CREDENTIALS=$HOME/gcloud.json
    - name: Create .firebaserc 
      run: echo '${{ secrets.FIREBASERC }}' > .firebaserc
    - uses: actions/setup-node@v3
      with:
        node-version: 18.2.0
    - name: npm install
      run: cd functions && npm install
    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
    - name: Deploy Cloud Functions
      run: npx firebase-tools deploy --project dev --only functions --json --force
